# Generated by Django 4.2.1 on 2023-10-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, unique=True, verbose_name='Название категории')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='category_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
    ]
