# Generated by Django 4.2.1 on 2023-10-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_descriptionpresent_product_hit_product_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salenum',
            field=models.CharField(max_length=3, null=True, verbose_name='Сумма скидки в процентах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна'),
        ),
    ]
