# Generated by Django 4.2.1 on 2023-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_salenum_alter_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.CharField(max_length=256, null=True, verbose_name='Применение *'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=50, null=True, verbose_name='Бренд *'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=3000, null=True, verbose_name='Описание *'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptionpresent',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание подарка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='effect',
            field=models.CharField(max_length=50, null=True, verbose_name='Эффект *'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hit',
            field=models.BooleanField(blank=True, null=True, verbose_name='Хит'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products_images', verbose_name='Изображение *'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='Название *'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(blank=True, null=True, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='present',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подарок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена *'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.BooleanField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salenum',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Сумма скидки в процентах (без символа %)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна *'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=10, null=True, verbose_name='Масса *'),
        ),
    ]
