# Generated by Django 4.2.1 on 2023-11-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_quantity_alter_product_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=2000, null=True, upload_to='products_images', verbose_name='Изображение: максимум 2000*2000*', width_field=2000),
        ),
    ]
