# Generated by Django 4.2.1 on 2023-10-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesite', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Название сайта')),
                ('descriptionsite', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание сайта')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон на сайте')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Адрес магазина')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='site_images', verbose_name='Фото-1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='site_images', verbose_name='Фото-2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='site_images', verbose_name='Фото-3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='site_images', verbose_name='Фото-4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='site_images', verbose_name='Фото-5')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название ИП')),
                ('nameip', models.CharField(max_length=50, null=True, verbose_name='Имя руководителя')),
                ('phonip', models.CharField(blank=True, max_length=15, verbose_name='Телефон руководителя')),
                ('inn', models.CharField(max_length=15, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=15, null=True, verbose_name='КПП')),
                ('rs', models.CharField(max_length=50, null=True, verbose_name='р/с')),
                ('bic', models.CharField(max_length=50, null=True, verbose_name='БИК')),
                ('bank', models.CharField(max_length=256, null=True, verbose_name='Полное наименование банка, включая номер отделения или дополнительного офиса и\xa0город')),
                ('ks', models.CharField(max_length=50, null=True, verbose_name='к/c')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
