# Generated by Django 4.2.1 on 2023-10-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsite',
            name='image',
            field=models.ImageField(null=True, upload_to='site_images', verbose_name='Изображение'),
        ),
    ]
