# Generated by Django 4.2.1 on 2023-10-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_settingsite_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsite',
            name='image',
            field=models.ImageField(null=True, upload_to='site_images', verbose_name='Изображение описания'),
        ),
    ]
